# Generated by Django 5.0.7 on 2025-02-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_geo_id', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoobjectcodesub',
            name='is_group',
            field=models.BooleanField(db_comment='{"name":"это группа объектов текущегосправочника?.""description":"это группа объектов текущегосправочника?"}', default=False, help_text='это группа объектов текущегосправочника?', verbose_name='это группа объектов текущегосправочника?'),
        ),
        migrations.AddField(
            model_name='historicalgeoobjectcodesub',
            name='is_group',
            field=models.BooleanField(db_comment='{"name":"это группа объектов текущегосправочника?.""description":"это группа объектов текущегосправочника?"}', default=False, help_text='это группа объектов текущегосправочника?', verbose_name='это группа объектов текущегосправочника?'),
        ),
    ]
