# Generated by Django 5.0.7 on 2025-02-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_geo_id', '0002_geoobjectcodesub_is_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoinfo',
            name='coordinates',
            field=models.TextField(blank=True, null=True, verbose_name='Площадь территории (кв2. км)'),
        ),
    ]
