# Generated by Django 5.0.7 on 2025-02-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_data_asset', '0002_alter_dataassetgroupasset_data_assets_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataasset',
            options={'ordering': ['name'], 'verbose_name': '01 Источник данных', 'verbose_name_plural': '01 Источники данных'},
        ),
        migrations.AlterModelOptions(
            name='datavalue',
            options={'ordering': ['-created_at'], 'verbose_name': '04 Значения таблицы', 'verbose_name_plural': '04 Значения таблицы'},
        ),
        migrations.AlterField(
            model_name='dataasset',
            name='url',
            field=models.URLField(blank=True, db_comment='{"name":"URL ссылка.",}', help_text='URL ссылка.', null=True, verbose_name='URL.'),
        ),
    ]
